In [1]:
from pymongo import MongoClient

In [2]:
conn = MongoClient('192.168.68.11', 20000)
db = conn.lawCase
all_info_set = db.lawcase

In [5]:
x = all_info_set.find_one()
print(x)

{'filepath': '/opt/new_lawcases/subfolder237/2426461.xml', '_id': ObjectId('5a31af330e2c810b3c742dd4'), 'text': ' 福建省仙游县人民法院 民事判决书 （2015）仙民初字第2164号 原告温丽容，女，1975年12月15日出生，汉族，住仙游县。 被告林文耀，男，1977年1月25日出生，汉族，住仙游县。 原告温丽容与被告林文耀因民间借贷纠纷一案，本院于2015年3月31日立案受理后，依法由审判员章建育适用简易程序公开开庭进行了审理。原告温丽容到庭参加诉讼，被告林文耀经本院传票传唤，无正当理由拒不到庭参加诉讼。本案现已审理终结。 原告诉称，2014年10月1日，被告向原告借款人民币30000元，没有约定借款利息和期限，有被告出具的欠条为证。借款后，原告多次向被告催讨欠款未果，故请求判令被告偿还给原告借款本金人民币30000元并支付自起诉之日起至还清借款之日止，以本金人民币30000元为基数，按中国人民银行规定的银行同类同期贷款利率计算的利息。 被告没有答辩。 现查明，被告曾向原告借款，尚欠原告借款人民币30000元未予偿还，没有约定利息和还款时间。2014年10月1日，被告出具欠条一份给原告收执为凭，欠条内容为：“欠条今向温丽容借人民币30000元（叁万元整）。借款人：林文耀2014．10．1”。其后，原告向被告催讨欠款未果，故诉至本院，请求处理。在审理期间，本院将原告的起诉状副本和证据复印件等诉讼材料送达给被告，被告没有提出答辩和反驳意见。在庭审中，原告提供被告出具的欠条一份，以证实自己的诉讼主张。本院审查认为，原告提供的证据，内容真实、来源合法，且与本案有关联，能够证明本案之事实情况，本院予以确认。 本院认为，合法的借贷关系受法律保护，且债务应当清偿。原告与被告之间因借贷形成的债权债务关系，当事人主体适格、意思表示真实，没有违反法律、行政法规之强制性规定，合法有效。被告结欠原告借款人民币30000元，没有约定还款时间，原告随时可要求被告返还，被告应当及时返还，否则应承担偿还借款并支付逾期利息的民事责任，故原告的诉讼请求合法有据，本院予以支持。被告经本院合法传唤，无正当理由拒不到庭，视为自动放弃诉讼权利，本院依法缺席审理和判决。据此，依照《中华人民共和国民法通则》第九十条、第一百零八条，最高人民法院《关于贯彻执行〈中华人民共和国民法通则〉若干问题的意见（试行）》第121条、第123条和《中华人民共和国民事诉讼法》第一百四十四条之规定，判决如下： 被告林文耀应在本判决生效之日起十日内偿还给原告温丽容借款人民币三万元并支付利息，利息计算方式：自二0一五年三月三十一日起，以本金人民币三万元为基数，按中国人民银行规定的银行同类同期贷款利率计至还清借款之日止。 被告如果未按本判决指定的期间履行给付金钱义务，应当依照《中华人民共和国民事诉讼法》第二百五十三条之规定，加倍支付迟延履行期间的债务利息。 案件受理费减半收取为人民币二百七十五元，由被告林文耀负担。 如不服本判决，可以在判决书送达之日起十五日内，向本院递交上诉状，并按对方当事人的人数或者代表人的人数提出副本，上诉于福建省莆田市中级人民法院。 审判员章建育 二〇一五年五月五日 书记员方瑞昌 一、引用的主要法律条款 1、《中华人民共和国民法通则》 第九十条合法的借贷关系受法律保护。 第一百零八条债务应当清偿。暂时无力偿还的，经债权人同意或者人民法院裁决，可以由债务人分期偿还。有能力偿还拒不偿还的，由人民法院判决强制偿还。 2、最高人民法院《关于贯彻执行〈中华人民共和国民法通则〉若干问题的意见（试行）》 121、公民之间的借贷，双方对返还期限有约定的，一般应按约定处理；没有约定的，出借人随时可以请求返还，借方应当根据出借人的请求及时返还；暂时无力返还的，可以根据实际情况责令其分期返还。 123、公民之间的无息借款，有约定偿还期限而借款人不按期偿还，或者未约定偿还期限但经出借人催告后，借款人仍不偿还的，出借人要求借款人偿付逾期利息，应当予以准许。 3、《中华人民共和国民事诉讼法》 第一百四十四条被告经传票传唤，无正当理由拒不到庭的，或者未经法庭许可中途退庭的，可以缺席判决。 第二百五十三条被执行人未按判决、裁定和其他法律文书指定的期间履行给付金钱义务的，应当加倍支付迟延履行期间的债务利息。被执行人未按判决、裁定和其他法律文书指定的期间履行其他义务的，应当支付迟延履行金。 二、执行申请 提示 《中华人民共和国民事诉讼法》第二百三十九条申请执行的期间为二年。申请执行时效的中止、中断，适用法律有关诉讼时效中止、中断的规定。 前款规定的期间，从法律文书规定履行期间的最后一日起计算；法律文书规定分期履行的，从规定的每次履行期间的最后一日起计算；法律文书未规定履行期间的，从法律文书生效之日起计算。 '}

In [6]:
all_info = []

myset = db.dataset
for i in myset.find().limit(50):
    all_info.append([i['codeOfCauseOfAction']])

NameError: name 'pd' is not defined

In [7]:
import pandas as pd
df = pd.DataFrame(all_info, columns=['code'])
df

    code
0   9135
1   9690
2   9462
3   1560
4   9395
5   9184
6   9196
7   9178
8   9568
9   9142
10  9722
11  9165
12  9075
13  9015
14  9057
15
16  9015
17  9211
18  9711
19  9462
20  9270
21  9164
22  9722
23  9138
24  9015
25  9280
26  9462
27  9580
28
29  9134
30  9003
31  9202
32  9003
33  9463
34  9722
35  9722
36  9015
37  9563
38  9722
39  9094
40  9462
41  9462
42  9401
43  9196
44  9462
45
46  9722
47  9025
48  9142
49  9133

In [13]:
print(df.loc[1])

code    9690
Name: 1, dtype: object